apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-rolebinding
subjects:
  - kind: ServiceAccount
    name: nginx-sa
roleRef:
  kind: Role
  name: nginx-role
  apiGroup: rbac.authorization.k8s.io
